module.exports = {
  AUTH_LOGOUT: 'AUTH_LOGOUT',
  AUTH_LOGIN_REQUEST: 'AUTH_LOGIN_REQUEST',
  AUTH_LOGOUT_REQUEST: 'AUTH_LOGOUT_REQUEST',
  AUTH_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUTH_LOGIN_FAIL: 'AUTH_LOGIN_FAIL',
  AUTH_CHECK_LOGGED_IN: 'AUTH_CHECK_LOGGED_IN'
}
