module.exports = {
  ENTER_EDIT_MODE: 'ENTER_EDIT_MODE',
  LEAVE_EDIT_MODE: 'LEAVE_EDIT_MODE',
  START_EDITING: 'START_EDITING',
  SHOW_EDIT_MODAL: 'SHOW_EDIT_MODAL',
  CLOSE_EDIT_MODAL: 'CLOSE_EDIT_MODAL',
  CHANGE_EDIT_MODE: 'CHANGE_EDIT_MODE',
}
