module.exports = {
  LOADING_NAV: 'LOADING_NAV',
  NAV_LOAD_SUCCESS: 'NAV_LOAD_SUCCESS',
  NAV_LOAD_FAIL: 'NAV_LOAD_FAIL',
  UPDATE_NAV: 'UPDATE_NAV',
  SAVING_NAV: 'SAVING_NAV',
  SAVING_NAV_SUCCESS: 'SAVING_NAV_SUCCESS',
  SAVING_NAV_FAIL: 'SAVING_NAV_FAIL',
  ADD_NAV_ELEMENT: 'ADD_NAV_ELEMENT',
}
